
```{r, echo = FALSE}
region_countries <- load_regions_countries()
n_unique_countries <- length( unique( data$SI01 ))
region_countries <- region_countries %>%
  filter(Region == params$region)
n_region_countries <- length( region_countries$Country)
```

`r str_to_title(as.english(n_unique_countries))` of `r n_region_countries` `r params$region` countries (`r round(100*( n_unique_countries / n_region_countries))`%) responded:  

`r pander( data$SI01 )`. 

```{r}
q5_start <- min(which(dict$`Question number` == "5"))
incomplete_surveys <- c()
for (i in 1:nrow(data)) {
  if (all(is.na(data[i, q5_start:nrow(dict)]))) {
    incomplete_surveys <- c(incomplete_surveys, i)
  }
}
incompletes <- FALSE
if( length( incomplete_surveys) > 0){
  incompletes <- TRUE
  excluded_countries <- paste( data$SI01[ incomplete_surveys ], "only provided initial demographic information; their responses are henceforth excluded.\n Non-responding countries are of concern in terms of arbovirus emergence and endemic transmission.")
} 
```

```{r eval=incompletes, results="asis"}
pander(excluded_countries)
```

```{r, out.width = '100%'}
load("../data/world_shp.rda")
library( leaflet )

# N.B. subsetting world_shp causes problems with certain versions of leaflet (?)
# leaving the following 2 lines for now in case they're useful later...
# rshape <- world_shp[ !is.na( world_shp@data$region ), ]
# rshape <- rshape[ rshape@data$region == params$region, ]

if( params$region != "WPRO" ){
  ll <- apply( coordinates(world_shp[ !is.na( world_shp@data$region ) & world_shp@data$region == params$region, ]), 2, mean )
} else{
  ll <- c( world_shp@data$LON[ which( world_shp@data$country == "Cambodia") ],
           world_shp@data$LAT[ which( world_shp@data$country == "Cambodia") ])
}
make_map(df = data %>% 
           dplyr::select(country = SI01) %>% 
           mutate( country = recode_factor(.x=country,
                                           "Bolivia (Plurinational State of)" = "Bolivia",
                                           "Saint Barthélemy" = "Saint Barthelemy",
                                           "United States of America" = "United States",
                                           "Venezuela (Bolivarian Republic of)" = "Venezuela") ) %>% 
           mutate(value = 'Participated'),
         pal = 'Set2', qualitative = TRUE, rev = FALSE, opacity = 0.95) %>%
  setView( lng = ll[1], lat = ll[2], zoom = case_when( params$region == "AMRO" ~ 2,
                                                       params$region == "EMRO" ~ 3,
                                                       params$region == "EURO" ~ 4,
                                                       params$region == "SEARO" ~ 3,
                                                       params$region == "WPRO" ~ 3) )
```
