
#### Presence _Aedes aegypti_ or _Aedes albopictus_ in the past 5 years (ref Q34)

```{r}
responses <- get_responses("34") 
responses <- cbind(Country=data$SI01, responses)
both <- responses$Country[ which(responses$Response == "Yes, both Aedes aegypti and Aedes albopictus" )]
aegypti <- responses$Country[ which(responses$Response == "Yes, only Aedes aegypti" )]
```

`r both` all indicated that both _Aedes aegypti_ and _Aedes albopictus_ were present, whereas `r aegypti` 
had only identified _Aedes aegypti_.

<br>

### Potential public health threat from _Aedes_ species by country

<br>

#### Potential public health threat from _Aedes_ species by country (ref Q34b, 34c)

```{r}
q34b <- get_responses("34b")
colnames( q34b ) <- c("Response", "Other")
q34b <- q34b %>%
  mutate( Response = factor( replace_na( as.character(Response), ""))) %>%
  mutate( Other = factor( replace_na( as.character(Other), ""))) %>%
  unite( Response, Response:Other, sep="") %>%
  rename("Aedes aegypti threat"=Response)
q34c <- get_responses("34c")
colnames( q34c ) <- c("Response", "Other")
q34c <- q34c %>%
  mutate( Response = factor( replace_na( as.character(Response), ""))) %>%
  mutate( Other = factor( replace_na( as.character(Other), ""))) %>%
  unite( Response, Response:Other, sep="") %>%
  rename("Aedes albopictus threat"=Response)

q34bc <- cbind( Country = data$SI01, q34b, q34c)
aegypti <- grep( "Aedes", q34bc[,2]) 
albopictus <- grep( "Aedes", q34bc[,3] )

ft34bc <- cbind( Country = data$SI01, q34b, q34c) %>% 
  regulartable( ) %>% 
  theme_zebra(odd_header="#048ECA", odd_body = "#D6EAF8") %>% 
  color( color="#FFFFFF", part="header" ) %>% 
  compose( j = 2, part="header", value = as_paragraph( as_i("Aedes aegypti"), " threat")) %>%
  compose( j = 3, part="header", value = as_paragraph( as_i("Aedes albopictus"), " threat")) %>%
  valign( valign = "top", part="header" ) %>%
  padding( padding.top = 10, part="all") %>%
  padding( padding.bottom = 10, part="all") %>%
  autofit()

prefix <- "Aedes aegypti"
for(i in aegypti){
  suffix <- unlist( str_split( ft34bc$body$dataset[i,2], prefix ) )[2]
  ft34bc <- ft34bc %>% compose( i=i, j=2, part="body", value = as_paragraph( as_i(prefix), suffix))
}

prefix <- "Aedes albopictus"
for(i in albopictus){
  suffix <- unlist( str_split( ft34bc$body$dataset[i,3], prefix ) )[2]
  ft34bc <- ft34bc %>% compose( i=i, j=3, part="body", value = as_paragraph( as_i(prefix), suffix))
}

ft34bc

```
