
#### Community outreach staff perceptions of factors contributing to the a) success and b) barriers/challenges with respect to community participation (ref Q46)

```{r}
amro <- params$region == "AMRO"
```

```{r eval = !amro}
successes_barriers <- read_csv("../data/Country_level_summarized_responses.csv")
successes_barriers <- successes_barriers %>%
  filter(Region == params$region ) %>%
  droplevels() %>%
  select( Country, Successes = Q46_successes, Barriers = Q46_barriers) 

responses <- get_responses("46")
cbind(Country=data$SI01, responses) %>%
  select( -Response ) %>% 
  left_join( successes_barriers, by="Country") %>%
  regulartable() %>%
  theme_zebra(odd_header="#048ECA", odd_body = "#D6EAF8") %>% 
  color( color="#FFFFFF", part="header" ) %>% 
  valign( valign = "top", part="header" ) %>%
  padding( padding.top = 10, part="all") %>%
  padding( padding.bottom = 10, part="all") %>%
  autofit()
```

```{r eval = amro}
disclaimer <- "#### Question 46 was not included in the dataset shared with AMRO for completion. Please see the Arbovirus Survey Overview for more information."
```

<br>

`r if(amro){ disclaimer }`
