---
title: 'Arboviral Surveillance and Response Capacity Survey 2021'
output: html_document
---

```{r, include=FALSE, echo = FALSE}
# Basic knitr options
library(knitr)
opts_chunk$set(comment = NA, 
               echo = FALSE,
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE)
```

```{r, echo = FALSE}
source('functions.R')
dict <- load_dict()
data <- load_data()
region_countries <- load_regions_countries()
```

```{r}
data <- data %>% mutate(SI01 = as.character(SI01)) %>% arrange( SI01 )
```

### Table 14

```{r}

q10 <- get_responses("10") %>% 
  select(-Other)
colnames(q10) <- c("Basic","Repeat_basic","Advanced","Repeat_advanced","None")
q10 <- cbind( Region = data$Region, q10 )  %>%
  mutate(
    Basic = (Basic == "Yes"),
    Repeat_basic = (Repeat_basic == "Yes"),
    Advanced = (Advanced == "Yes"),
    Repeat_advanced = (Repeat_advanced == "Yes"),
    None = (None == "Yes")
  )  %>%
  mutate( Training = ( Basic | Repeat_basic | Advanced | Repeat_advanced ),
          Answered = (Training | None ) ) %>%
  filter( Answered ) %>% 
  group_by( Region ) %>% 
  summarize( Yes = sum( Training, na.rm=TRUE ),
             Percentage = paste0( "(", round(100*Yes / n() ) , "%)" ) ) %>%
  unite( "Disease surveillance", Yes:Percentage, sep = "\n" )

q19d <- get_responses("19d")
q19d <- cbind( Region = data$Region, q19d ) %>%
  filter( Response %in% c("Yes", "No") ) %>%
  mutate( Response = (Response == "Yes" ) ) %>%
  group_by( Region ) %>%
  summarize( Yes = sum( Response ),
             Percentage = paste0( "(", round(100*Yes / n() ) , "%)" ) ) %>%
  unite( "Diagnosis & case notification", Yes:Percentage, sep = "\n" )


q24 <- get_responses("24") %>%
  select( Response )
q24 <- cbind( Region = data$Region, q24 ) %>%
  mutate( Response = ifelse( grepl("Yes", Response, fixed = TRUE), "Yes", Response )) %>% 
  filter( Response %in% c("Yes", "No") ) %>%
  mutate( Response = (Response == "Yes" ) ) %>%
  group_by( Region ) %>%
  summarize( Yes = sum( Response ),
             Percentage = paste0( "(", round(100*Yes / n() ) , "%)" ) ) %>%
  unite( "Management of arboviral disease cases", Yes:Percentage, sep = "\n" )

q36 <- get_responses("36") 
q36 <- cbind( Region = data$Region, q36 ) %>%
  mutate( Response = ifelse( grepl("Yes", Response, fixed = TRUE), "Yes", Response )) %>% 
  filter( Response %in% c("Yes", "No") ) %>%
  mutate( Response = (Response == "Yes" ) ) %>%
  group_by( Region ) %>%
  summarize( Yes = sum( Response ),
             Percentage = paste0( "(", round(100*Yes / n() ) , "%)" ) ) %>%
  unite( "Routine vector surveillance and control", Yes:Percentage, sep = "\n" )

q45 <- get_responses("45") %>%
  select( Response )
q45 <- cbind( Region = data$Region, q45 ) %>%
  mutate( Response = ifelse( grepl("Yes", Response, fixed = TRUE), "Yes", Response )) %>% 
  filter( Response %in% c("Yes", "No") ) %>%
  mutate( Response = (Response == "Yes" ) ) %>%
  group_by( Region ) %>%
  summarize( Yes = sum( Response ),
             Percentage = paste0( "(", round(100*Yes / n() ) , "%)" ) ) %>%
  unite( "Community sensitization & participation", Yes:Percentage, sep = "\n" )

q53 <- get_responses("53") 
q53 <- cbind( Region = data$Region, q53 ) %>%
  filter( Response %in% c("Yes", "No") ) %>%
  mutate( Response = (Response == "Yes" ) ) %>%
  group_by( Region ) %>%
  summarize( Yes = sum( Response ),
             Percentage = paste0( "(", round(100*Yes / n() ) , "%)" ) ) %>%
  unite( "Preparedness for arboviral outbreaks or epidemics", Yes:Percentage, sep = "\n" )

table14 <- left_join( q10, q19d, by = "Region") %>%
  left_join( q24, by = "Region" ) %>% 
  left_join( q36, by = "Region" ) %>% 
  left_join( q45, by = "Region" ) %>%
  left_join( q53, by = "Region")

regulartable( table14 ) %>% 
  theme_zebra(odd_header="#048ECA", odd_body = "#D6EAF8") %>% 
  footnote( j=2:7, 
            part = "header", 
            value = as_paragraph( c("Only countries that responded to Q10, Q19d, Q24, Q36, Q45, and Q53, respectively, are included in the denominator when calculating these percentages. These questions were not included in the dataset shared with AMRO for completion; please see the Arbovirus Survey Overview for more information.") ),
            ref_symbols = c("a") ) %>%
  color( color="#FFFFFF", part="header" ) %>% 
  align( j=2:7, align="center", part="all") %>%
  valign( valign = "top", part="header" ) %>%
  padding( padding.top = 10, part="all") %>%
  padding( padding.bottom = 10, part="all") %>%
  autofit()

```

