
### Arbovirus laboratory capacity

#### Testing capacity by virus and assay type (ref Q17)

```{r}
responses <- get_responses("17")
responses <- cbind(Region = data$Region, responses) %>%
  filter( if_any(!Region, ~ !is.na(.x))) 
nums <- responses %>% 
  group_by(Region) %>% 
  tally( name = "n_countries")
responses <- responses %>% 
  pivot_longer(!Region)

new_cols <- matrix(unlist(strsplit(responses$name, "\\]\\[")), ncol = 2, byrow = T)
responses <- responses %>%
  mutate(Level = new_cols[, 1], Test = new_cols[, 2]) %>%
  select(-name) %>%
  filter( Level != "Other") %>% 
  # mutate( value = as.character(value)) %>%
  replace_na(list(value = 0)) %>%
  mutate( Region = as.factor(Region)) %>% 
  mutate( Level = recode_factor(.x = Level,
                                    "Chikungunya"="CHIKV",
                                    "Dengue"="DENV",
                                    "Yellow fever"="YFV",
                                    "Zika"="ZIKV")) %>%
  mutate( Test = as.factor(Test)) %>% 
  mutate( value = as.numeric( value )) %>%
  filter( Test %in% c("Antigen testing",
                      "IgG antibody testing",
                      "IgM antibody testing",
                      "Neutralizing antibody testing",
                      "RT-PCR or other nucleic acid amplification test")) %>%
  droplevels() 

chikv_denv <- responses %>% 
  filter( Level == "CHIKV" | Level == "DENV")

yfv_zikv <- responses %>% 
  filter( Level == "YFV" | Level == "ZIKV")

chikv_denv <- chikv_denv %>% 
  group_by(Region,Level,Test) %>% 
  summarize( Total = sum(value) ) %>% 
  ungroup() %>%
  left_join( nums, by="Region") %>%
  mutate( Total = paste0(Total, "\n(",round(100*Total/n_countries),"%)") ) %>%
  select( -n_countries ) %>%
  mutate( Test = recode_factor( .x=Test,
                                "Antigen testing"="A",
                                "IgM antibody testing"="M",
                                "IgG antibody testing"="G",
                                "Neutralizing antibody testing"="N",
                                "RT-PCR or other nucleic acid amplification test"="P")) %>%
  pivot_wider( names_from = Level:Test, values_from = Total, names_sort = TRUE) %>%
  rename("Regional office" = "Region")

chikv_denv_header <- data.frame( keys = c("Regional office", "blank1", 
                                     "CHIKV_A", "CHIKV_M", "CHIKV_G", "CHIKV_N", "CHIKV_P", "blank2",
                                     "DENV_A", "DENV_M", "DENV_G", "DENV_N", "DENV_P", "blank3" ) )
chikv_denv_header <- cbind( chikv_denv_header, separate( chikv_denv_header,keys, into=c("Virus", "Test"), sep="_"))
chikv_denv_header$Test[1] <- chikv_denv_header$keys[1]
chikv_denv_header$Virus[ c(2,8,14)] <- ""
chikv_denv_header$Test[ c(2,8,14)] <- ""

chikv_denv %>%
  flextable( col_keys = chikv_denv_header$keys ) %>%
  set_header_df( mapping = chikv_denv_header, key="keys") %>%
  merge_h( part="header") %>%
  merge_v( j=1, part="header") %>%
  theme_zebra(odd_header="#048ECA", even_header="#048ECA", odd_body = "#D6EAF8") %>% 
  footnote( i = 1, j=c(3:7,9:13), 
            part = "header", 
            value = as_paragraph("Only countries that responded to Q17 are included in the denominator when calculating these percentages"),
            ref_symbols = "a") %>%
  footnote( i = 2, j=c(3:7,9:13),
            part = "header",
            value = as_paragraph("A = Antigen testing; M = IgM antibody testing; G = IgG antibody testing; N = Neutralizing antibody testing; P = RT-PCR or other nucleic acid amplification test"),
            ref_symbols = "b" ) %>%
  color( color="#FFFFFF", part="header" ) %>% 
  align( align="center", part="all") %>%
  align( align="left", j=1, part="all" ) %>%
  valign( valign = "top", part="header" ) %>%
  padding( padding.top = 10, part="all") %>%
  padding( padding.bottom = 10, part="all") %>%
  hline( i=1, j = 3:7, part="header", border = fp_border(width = 2, color = "#FFFFFF")) %>%
  hline( i=1, j = 9:13, part="header", border = fp_border(width = 2, color = "#FFFFFF")) %>%
  autofit()
```

<br>


```{r}
yfv_zikv <- yfv_zikv %>% 
  group_by(Region,Level,Test) %>% 
  summarize( Total = sum(value) ) %>% 
  ungroup() %>%
  left_join( nums, by="Region") %>%
  mutate( Total = paste0(Total, "\n(",round(100*Total/n_countries),"%)") ) %>%
  select( -n_countries ) %>%
  mutate( Test = recode_factor( .x=Test,
                                "Antigen testing"="A",
                                "IgM antibody testing"="M",
                                "IgG antibody testing"="G",
                                "Neutralizing antibody testing"="N",
                                "RT-PCR or other nucleic acid amplification test"="P")) %>%
  pivot_wider( names_from = Level:Test, values_from = Total, names_sort = TRUE) %>%
  rename("Regional office" = "Region")

yfv_zikv_header <- data.frame( keys = c("Regional office", "blank1", 
                                     "YFV_A", "YFV_M", "YFV_G", "YFV_N", "YFV_P", "blank2",
                                     "ZIKV_A", "ZIKV_M", "ZIKV_G", "ZIKV_N", "ZIKV_P", "blank3") )
yfv_zikv_header <- cbind( yfv_zikv_header, separate( yfv_zikv_header,keys, into=c("Virus", "Test"), sep="_"))
yfv_zikv_header$Test[1] <- yfv_zikv_header$keys[1]
yfv_zikv_header$Virus[ c(2,8,14)] <- ""
yfv_zikv_header$Test[ c(2,8,14)] <- ""

yfv_zikv %>%
  flextable( col_keys = yfv_zikv_header$keys ) %>%
  set_header_df( mapping = yfv_zikv_header, key="keys") %>%
  merge_h( part="header") %>%
  merge_v( j=1, part="header") %>%
  theme_zebra(odd_header="#048ECA", even_header="#048ECA", odd_body = "#D6EAF8") %>% 
  footnote( i = 1, j=c(3:7,9:13), 
            part = "header", 
            value = as_paragraph("Only countries that responded to Q17 are included in the denominator when calculating these percentages."),
            ref_symbols = "a") %>%
  footnote( i = 2, j=c(3:7,9:13),
            part = "header",
            value = as_paragraph("A = Antigen testing; M = IgM antibody testing; G = IgG antibody testing; N = Neutralizing antibody testing; P = RT-PCR or other nucleic acid amplification test"),
            ref_symbols = "b" ) %>%
  color( color="#FFFFFF", part="header" ) %>% 
  align( align="center", part="all") %>%
  align( align="left", j=1, part="all" ) %>%
  valign( valign = "top", part="header" ) %>%
  padding( padding.top = 10, part="all") %>%
  padding( padding.bottom = 10, part="all") %>%
  hline( i=1, j = 3:7, part="header", border = fp_border(width = 2, color = "#FFFFFF")) %>%
  hline( i=1, j = 9:13, part="header", border = fp_border(width = 2, color = "#FFFFFF")) %>%
  autofit()

```

