---
title: ' '
pagetitle: 'EMRO Q15'
output:
  html_document:
    includes:
      in_header: EMRO_Q15_header.html
params:
  region: EMRO
---

```{r, include=FALSE, echo = FALSE}
# Basic knitr options
library(knitr)
opts_chunk$set(comment = NA, 
               echo = FALSE,
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE)
```

```{js}
// Region dropdown
/* When the user clicks on the button,
toggle between hiding and showing the dropdown content */
function myFunction() {
  document.getElementById("myDropdown").classList.toggle("show");
}

// Close the dropdown menu if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {
    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
// end region dropdown

element = document.getElementById('WHO_logo');
console.log(element)

$('#WHO_logo').click(function(e){
    console.log("Exists!")
});


window.onscroll = function() { scrollFunction() };

var navbar = document.getElementById("navbar");
var logoWhiteElement = document.getElementById("whiteLogoPosition")
var sticky = navbar.offsetTop;

function scrollFunction() {
  if (window.pageYOffset >= sticky) {
    navbar.classList.add("sticky");
    logoWhiteElement.classList.add("white_logo_appear");
  } else {
    navbar.classList.remove("sticky");
    logoWhiteElement.classList.remove("white_logo_appear");
  }
}

$(document).on('click', function (e){
    /* Overview of data  */
    var overview_menu_opened = $('#overview-navigation').hasClass('in');
    if(!$(e.target).closest('#overview-navigation').length &&
        !$(e.target).is('#overview-navigation') &&
        overview_menu_opened === true){
            $('#overview-navigation').collapse('toggle');
            $( "#Overview-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#overview-navigation').attr('aria-expanded') === "false") {
      $( "#Overview-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#overview-navigation').attr('aria-expanded') === "true") {
      $( "#Overview-Li-area" ).addClass("activeMenuState");
    }
    
    /* Global data  */
    var global_menu_opened = $('#global-navigation').hasClass('in');
    if(!$(e.target).closest('#global-navigation').length &&
        !$(e.target).is('#global-navigation') &&
        global_menu_opened === true){
            $('#global-navigation').collapse('toggle');
            $( "#Global-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#global-navigation').attr('aria-expanded') === "false") {
      $( "#Global-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#global-navigation').attr('aria-expanded') === "true") {
      $( "#Global-Li-area" ).addClass("activeMenuState");
    }

     /* Regional data  */
    var regional_menu_opened = $('#regional-navigation').hasClass('in');
    if(!$(e.target).closest('#regional-navigation').length &&
        !$(e.target).is('#regional-navigation') &&
        regional_menu_opened === true) {
            $('#regional-navigation').collapse('toggle');
            $( "#Regional-Li-area" ).removeClass("activeMenuState");
    }
    
    /* #regional-navigation-disease-surveillance  */
    var regional_menu_opened = $('#regional-navigation-disease-surveillance').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-disease-surveillance').length &&
        !$(e.target).is('#regional-navigation-disease-surveillance') &&
        regional_menu_opened === true) {
            $('#regional-navigation-disease-surveillance').collapse('toggle');
    }
    
    /* #regional-navigation-lab-capacity  */
    var regional_menu_opened = $('#regional-navigation-lab-capacity').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-lab-capacity').length &&
        !$(e.target).is('#regional-navigation-lab-capacity') &&
        regional_menu_opened === true) {
            $('#regional-navigation-lab-capacity').collapse('toggle');
    }
    
    /* #regional-navigation-management  */
    var regional_menu_opened = $('#regional-navigation-management').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-management').length &&
        !$(e.target).is('#regional-navigation-management') &&
        regional_menu_opened === true) {
            $('#regional-navigation-management').collapse('toggle');
    }
    
    /* #regional-navigation-vector-surveillance  */
    var regional_menu_opened = $('#regional-navigation-vector-surveillance').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-vector-surveillance').length &&
        !$(e.target).is('#regional-navigation-vector-surveillance') &&
        regional_menu_opened === true) {
            $('#regional-navigation-vector-surveillance').collapse('toggle');
    }
    
    /* #regional-navigation-community  */
    var regional_menu_opened = $('#regional-navigation-community').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-community').length &&
        !$(e.target).is('#regional-navigation-community') &&
        regional_menu_opened === true) {
            $('#regional-navigation-community').collapse('toggle');
    }
    
    /* #regional-navigation-preparedness  */
    var regional_menu_opened = $('#regional-navigation-preparedness').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-preparedness').length &&
        !$(e.target).is('#regional-navigation-preparedness') &&
        regional_menu_opened === true) {
            $('#regional-navigation-preparedness').collapse('toggle');
    }
    
    /* #regional-navigation-surveillance-staffing  */
    var regional_menu_opened = $('#regional-navigation-surveillance-staffing').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-surveillance-staffing').length &&
        !$(e.target).is('#regional-navigation-surveillance-staffing') &&
        regional_menu_opened === true) {
            $('#regional-navigation-surveillance-staffing').collapse('toggle');
    }
    
    if ($('#regional-navigation').attr('aria-expanded') === "false") {
      $( "#Regional-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#regional-navigation').attr('aria-expanded') === "true") {
      $( "#Regional-Li-area" ).addClass("activeMenuState");
    }
     
     /* Country data  */
    var country_menu_opened = $('#country-navigation').hasClass('in');
    if(!$(e.target).closest('#country-navigation').length &&
        !$(e.target).is('#country-navigation') &&
        country_menu_opened === true){
            $('#country-navigation').collapse('toggle');
            $( "#Country-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#country-navigation').attr('aria-expanded') === "false") {
      $( "#Country-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#country-navigation').attr('aria-expanded') === "true") {
      $( "#Country-Li-area" ).addClass("activeMenuState");
    }

});

```

```{r, echo = FALSE}
source('functions.R')
dict <- load_dict()
data <- load_data()
region_countries <- load_regions_countries()
```

```{r}
data <- data %>% filter(Region==params$region) %>% droplevels() %>% mutate(SI01 = as.character(SI01)) %>% arrange( SI01 )
```

### Cases for which arbovirus laboratory testing is performed

#### Cases for which laboratory testing is performed by transmission period (ref Q15)

```{r}
responses <- get_responses("15")
periods <- colnames(responses)
colnames(responses)=c("Outbreak","Non")
responses <- cbind(Country = data$SI01, responses) %>% 
  mutate( Outbreak = recode_factor(Outbreak,
                                   "All suspect cases tested"="A",
                                   "Subset of suspect cases tested"="S",
                                   "No suspect cases tested"="N")) %>%
  mutate( Non = recode_factor(Non,
                                   "All suspect cases tested"="A",
                                   "Subset of suspect cases tested"="S",
                                   "No suspect cases tested"="N")) 
  
colnames(responses) <- c("Country",periods)
responses %>%
  regulartable() %>% 
  theme_zebra(odd_header="#048ECA", odd_body = "#D6EAF8") %>% 
  color( color="#FFFFFF", part="header" ) %>% 
  padding( padding.top = 10, part="all") %>%
  padding( padding.bottom = 10, part="all") %>%
  autofit()
```

<ul style="margin-left: 40px;">
<li> 
<strong>Cases tested</strong>: A = all suspect cases ; S = subset of suspect cases ; N = none
</li>
</ul>

<br>

### Viruses for which the national laboratory confirmed cases

#### Virus diagnostic confirmatory testing performed by the national laboratory (ref Q16)

```{r}
responses <- get_responses("16")
colnames(responses) <- c("Response","Arbovirus(es)")
responses <- responses %>%
  mutate(Response = recode_factor(Response,
                                  "Yes, for all arboviral infections. Please specify them:"="Yes",
                                  "Yes, but only for some arboviral infections. Please specify them:"="Yes",
                                  "No"="No"))
cbind(Country = data$SI01, responses) %>% 
  filter( Response == "Yes") %>%
  select(-Response) %>%
  replace_na( list("Arbovirus(es)"="Not specified")) %>%
  regulartable() %>% 
  theme_zebra(odd_header="#048ECA", odd_body = "#D6EAF8") %>% 
  color( color="#FFFFFF", part="header" ) %>% 
  padding( padding.top = 10, part="all") %>%
  padding( padding.bottom = 10, part="all") %>%
  autofit()
```

<ul style="margin-left: 40px;">
<li>
<strong>Virus acronyms</strong>: CCHFV = Crimean Congo haemorrhagic fever virus; CHIKV = chikungunya virus; DENV = dengue virus; EEEV = Eastern equine encephalitis virus; MAYV = Mayaro virus; OROV = Oropouche virus; RVFV = Rift Valley fever virus; SFFV = Sand fly fever virus (Naples, Sicilian); TBEV = Tick-borne encephalitis virus; TOSV = Toscana virus; VEEV = Venezuelan equine encephalitis virus; WNV = West Nile virus; YFV = yellow fever virus
</li>
</ul>
