---
title: ' '
pagetitle: 'EMRO Q12 global'
output:
  html_document:
    includes:
      in_header: EMRO_Q12_global_header.html
params:
  region: EMRO
---

```{r, include=FALSE, echo = FALSE}
# Basic knitr options
library(knitr)
opts_chunk$set(comment = NA, 
               echo = FALSE,
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE)
# ggplot2::theme_set(ggplot2::theme_bw())
```

```{js}
// Region dropdown
/* When the user clicks on the button,
toggle between hiding and showing the dropdown content */
function myFunction() {
  document.getElementById("myDropdown").classList.toggle("show");
}

// Close the dropdown menu if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {
    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
// end region dropdown

element = document.getElementById('WHO_logo');
console.log(element)

$('#WHO_logo').click(function(e){
    console.log("Exists!")
});


window.onscroll = function() { scrollFunction() };

var navbar = document.getElementById("navbar");
var logoWhiteElement = document.getElementById("whiteLogoPosition")
var sticky = navbar.offsetTop;

function scrollFunction() {
  if (window.pageYOffset >= sticky) {
    navbar.classList.add("sticky");
    logoWhiteElement.classList.add("white_logo_appear");
  } else {
    navbar.classList.remove("sticky");
    logoWhiteElement.classList.remove("white_logo_appear");
  }
}

$(document).on('click', function (e){
    /* Overview of data  */
    var overview_menu_opened = $('#overview-navigation').hasClass('in');
    if(!$(e.target).closest('#overview-navigation').length &&
        !$(e.target).is('#overview-navigation') &&
        overview_menu_opened === true){
            $('#overview-navigation').collapse('toggle');
            $( "#Overview-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#overview-navigation').attr('aria-expanded') === "false") {
      $( "#Overview-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#overview-navigation').attr('aria-expanded') === "true") {
      $( "#Overview-Li-area" ).addClass("activeMenuState");
    }
    
    /* Global data  */
    var global_menu_opened = $('#global-navigation').hasClass('in');
    if(!$(e.target).closest('#global-navigation').length &&
        !$(e.target).is('#global-navigation') &&
        global_menu_opened === true){
            $('#global-navigation').collapse('toggle');
            $( "#Global-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#global-navigation').attr('aria-expanded') === "false") {
      $( "#Global-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#global-navigation').attr('aria-expanded') === "true") {
      $( "#Global-Li-area" ).addClass("activeMenuState");
    }

     /* Regional data  */
    var regional_menu_opened = $('#regional-navigation').hasClass('in');
    if(!$(e.target).closest('#regional-navigation').length &&
        !$(e.target).is('#regional-navigation') &&
        regional_menu_opened === true) {
            $('#regional-navigation').collapse('toggle');
            $( "#Regional-Li-area" ).removeClass("activeMenuState");
    }
    
    /* #regional-navigation-disease-surveillance  */
    var regional_menu_opened = $('#regional-navigation-disease-surveillance').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-disease-surveillance').length &&
        !$(e.target).is('#regional-navigation-disease-surveillance') &&
        regional_menu_opened === true) {
            $('#regional-navigation-disease-surveillance').collapse('toggle');
    }
    
    /* #regional-navigation-lab-capacity  */
    var regional_menu_opened = $('#regional-navigation-lab-capacity').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-lab-capacity').length &&
        !$(e.target).is('#regional-navigation-lab-capacity') &&
        regional_menu_opened === true) {
            $('#regional-navigation-lab-capacity').collapse('toggle');
    }
    
    /* #regional-navigation-management  */
    var regional_menu_opened = $('#regional-navigation-management').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-management').length &&
        !$(e.target).is('#regional-navigation-management') &&
        regional_menu_opened === true) {
            $('#regional-navigation-management').collapse('toggle');
    }
    
    /* #regional-navigation-vector-surveillance  */
    var regional_menu_opened = $('#regional-navigation-vector-surveillance').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-vector-surveillance').length &&
        !$(e.target).is('#regional-navigation-vector-surveillance') &&
        regional_menu_opened === true) {
            $('#regional-navigation-vector-surveillance').collapse('toggle');
    }
    
    /* #regional-navigation-community  */
    var regional_menu_opened = $('#regional-navigation-community').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-community').length &&
        !$(e.target).is('#regional-navigation-community') &&
        regional_menu_opened === true) {
            $('#regional-navigation-community').collapse('toggle');
    }
    
    /* #regional-navigation-preparedness  */
    var regional_menu_opened = $('#regional-navigation-preparedness').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-preparedness').length &&
        !$(e.target).is('#regional-navigation-preparedness') &&
        regional_menu_opened === true) {
            $('#regional-navigation-preparedness').collapse('toggle');
    }
    
    /* #regional-navigation-surveillance-staffing  */
    var regional_menu_opened = $('#regional-navigation-surveillance-staffing').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-surveillance-staffing').length &&
        !$(e.target).is('#regional-navigation-surveillance-staffing') &&
        regional_menu_opened === true) {
            $('#regional-navigation-surveillance-staffing').collapse('toggle');
    }
    
    if ($('#regional-navigation').attr('aria-expanded') === "false") {
      $( "#Regional-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#regional-navigation').attr('aria-expanded') === "true") {
      $( "#Regional-Li-area" ).addClass("activeMenuState");
    }
     
     /* Country data  */
    var country_menu_opened = $('#country-navigation').hasClass('in');
    if(!$(e.target).closest('#country-navigation').length &&
        !$(e.target).is('#country-navigation') &&
        country_menu_opened === true){
            $('#country-navigation').collapse('toggle');
            $( "#Country-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#country-navigation').attr('aria-expanded') === "false") {
      $( "#Country-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#country-navigation').attr('aria-expanded') === "true") {
      $( "#Country-Li-area" ).addClass("activeMenuState");
    }

});

```

```{css, echo=FALSE}
h4 {
  text-align: center;
}
```

```{r, echo = FALSE}
source('functions.R')
dict <- load_dict()
data <- load_data()
```

```{r}
data <- data %>% mutate(SI01 = as.character(SI01)) %>% arrange( SI01 )
```

### Arbovirus disease surveillance planning and practice

#### Performance of national epidemiological surveillance for arboviral diseases in humans (ref Q12, 12b, 12c)

```{r}
responses_12 <- get_responses("12") 
responses_12 <- cbind( Region = data$Region, responses_12 )
nums <- responses_12 %>%
  group_by(Region) %>%
  tally( name = "n_countries")
responses_12 <- responses_12 %>%
  filter( Response == "Yes" ) %>%
  group_by( Region ) %>%
  tally() %>%
  ungroup() %>%
  left_join( nums, by="Region") %>%
  mutate( Percentage = 100*round(n/n_countries,3) ) %>%
  select( Region, Percentage) %>%
  mutate( across(!Region, ~ paste0(., "%"))) %>%
  rename( "Percentage conducting surveillance" = Percentage) 

responses_12b <- get_responses("12b")
colnames( responses_12b ) <- c("Response", "Other")
responses_12b$Other[ which(!is.na( responses_12b$Other )) ] <- "Other"
responses_12b <- responses_12b %>%
  mutate( Response = factor( replace_na( as.character(Response), ""))) %>%
  mutate( Other = factor( replace_na( as.character(Other), ""))) %>%
  unite( Frequency, Response:Other, sep="") 
responses_12b <- cbind( Region = data$Region, responses_12b ) %>%
  group_by(Region, Frequency) %>% 
  tally() %>%
  ungroup()
responses_12b$Frequency[ which( responses_12b$Frequency == "" ) ] <- "Unanswered"
responses_12b <- responses_12b %>% 
  left_join( nums, by="Region" ) %>%
  mutate( Percentage = paste0(100*round(n/n_countries, 3), "%") ) %>%
  select( Region, Frequency, Percentage ) %>%
  group_by(Region) %>% 
  summarize( "Surveillance frequency" = paste0(Frequency, collapse = "\n\n"),
             "Frequency %" = paste0(Percentage, collapse = "\n\n"))

responses_12c <- get_responses("12c")
colnames(responses_12c) <- "Type"
responses_12c <- cbind( Region = data$Region, responses_12c ) %>%
  group_by(Region, Type) %>% 
  tally() %>%
  ungroup() %>% 
  replace_na( list( Type = "Unanswered" )) %>% 
  left_join( nums, by="Region" ) %>%
  mutate( Percentage = paste0(100*round(n/n_countries, 3), "%") ) %>%
  select( Region, Type, Percentage ) %>%
  group_by(Region) %>% 
  summarize( "Surveillance type" = paste0(Type, collapse = "\n\n"),
             "Type %" = paste0(Percentage, collapse = "\n\n"))

responses_12 <- left_join( responses_12, responses_12b, by="Region") %>%
  left_join( responses_12c, by="Region")

responses_12 %>% 
  regulartable() %>% 
  # merge_v( j=1:2 ) %>%
  theme_zebra(odd_header="#048ECA", odd_body = "#D6EAF8") %>% 
  color( color="#FFFFFF", part="header" ) %>% 
  autofit()

```

<br>
