---
title: ' '
pagetitle: 'EURO participation'
output:
  html_document:
    includes:
      in_header: EURO_participation_header.html
params:
  region: EURO
---

```{r, include=FALSE, echo = FALSE}
# Basic knitr options
library(knitr)
opts_chunk$set(comment = NA, 
               echo = FALSE,
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE)
```

```{js}
// Region dropdown
/* When the user clicks on the button,
toggle between hiding and showing the dropdown content */
function myFunction() {
  document.getElementById("myDropdown").classList.toggle("show");
}

// Close the dropdown menu if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {
    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
// end region dropdown

element = document.getElementById('WHO_logo');
console.log(element)

$('#WHO_logo').click(function(e){
    console.log("Exists!")
});


window.onscroll = function() { scrollFunction() };

var navbar = document.getElementById("navbar");
var logoWhiteElement = document.getElementById("whiteLogoPosition")
var sticky = navbar.offsetTop;

function scrollFunction() {
  if (window.pageYOffset >= sticky) {
    navbar.classList.add("sticky");
    logoWhiteElement.classList.add("white_logo_appear");
  } else {
    navbar.classList.remove("sticky");
    logoWhiteElement.classList.remove("white_logo_appear");
  }
}

$(document).on('click', function (e){
    /* Overview of data  */
    var overview_menu_opened = $('#overview-navigation').hasClass('in');
    if(!$(e.target).closest('#overview-navigation').length &&
        !$(e.target).is('#overview-navigation') &&
        overview_menu_opened === true){
            $('#overview-navigation').collapse('toggle');
            $( "#Overview-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#overview-navigation').attr('aria-expanded') === "false") {
      $( "#Overview-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#overview-navigation').attr('aria-expanded') === "true") {
      $( "#Overview-Li-area" ).addClass("activeMenuState");
    }
    
    /* Global data  */
    var global_menu_opened = $('#global-navigation').hasClass('in');
    if(!$(e.target).closest('#global-navigation').length &&
        !$(e.target).is('#global-navigation') &&
        global_menu_opened === true){
            $('#global-navigation').collapse('toggle');
            $( "#Global-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#global-navigation').attr('aria-expanded') === "false") {
      $( "#Global-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#global-navigation').attr('aria-expanded') === "true") {
      $( "#Global-Li-area" ).addClass("activeMenuState");
    }

     /* Regional data  */
    var regional_menu_opened = $('#regional-navigation').hasClass('in');
    if(!$(e.target).closest('#regional-navigation').length &&
        !$(e.target).is('#regional-navigation') &&
        regional_menu_opened === true) {
            $('#regional-navigation').collapse('toggle');
            $( "#Regional-Li-area" ).removeClass("activeMenuState");
    }
    
    /* #regional-navigation-disease-surveillance  */
    var regional_menu_opened = $('#regional-navigation-disease-surveillance').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-disease-surveillance').length &&
        !$(e.target).is('#regional-navigation-disease-surveillance') &&
        regional_menu_opened === true) {
            $('#regional-navigation-disease-surveillance').collapse('toggle');
    }
    
    /* #regional-navigation-lab-capacity  */
    var regional_menu_opened = $('#regional-navigation-lab-capacity').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-lab-capacity').length &&
        !$(e.target).is('#regional-navigation-lab-capacity') &&
        regional_menu_opened === true) {
            $('#regional-navigation-lab-capacity').collapse('toggle');
    }
    
    /* #regional-navigation-management  */
    var regional_menu_opened = $('#regional-navigation-management').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-management').length &&
        !$(e.target).is('#regional-navigation-management') &&
        regional_menu_opened === true) {
            $('#regional-navigation-management').collapse('toggle');
    }
    
    /* #regional-navigation-vector-surveillance  */
    var regional_menu_opened = $('#regional-navigation-vector-surveillance').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-vector-surveillance').length &&
        !$(e.target).is('#regional-navigation-vector-surveillance') &&
        regional_menu_opened === true) {
            $('#regional-navigation-vector-surveillance').collapse('toggle');
    }
    
    /* #regional-navigation-community  */
    var regional_menu_opened = $('#regional-navigation-community').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-community').length &&
        !$(e.target).is('#regional-navigation-community') &&
        regional_menu_opened === true) {
            $('#regional-navigation-community').collapse('toggle');
    }
    
    /* #regional-navigation-preparedness  */
    var regional_menu_opened = $('#regional-navigation-preparedness').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-preparedness').length &&
        !$(e.target).is('#regional-navigation-preparedness') &&
        regional_menu_opened === true) {
            $('#regional-navigation-preparedness').collapse('toggle');
    }
    
    /* #regional-navigation-surveillance-staffing  */
    var regional_menu_opened = $('#regional-navigation-surveillance-staffing').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-surveillance-staffing').length &&
        !$(e.target).is('#regional-navigation-surveillance-staffing') &&
        regional_menu_opened === true) {
            $('#regional-navigation-surveillance-staffing').collapse('toggle');
    }
    
    if ($('#regional-navigation').attr('aria-expanded') === "false") {
      $( "#Regional-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#regional-navigation').attr('aria-expanded') === "true") {
      $( "#Regional-Li-area" ).addClass("activeMenuState");
    }
     
     /* Country data  */
    var country_menu_opened = $('#country-navigation').hasClass('in');
    if(!$(e.target).closest('#country-navigation').length &&
        !$(e.target).is('#country-navigation') &&
        country_menu_opened === true){
            $('#country-navigation').collapse('toggle');
            $( "#Country-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#country-navigation').attr('aria-expanded') === "false") {
      $( "#Country-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#country-navigation').attr('aria-expanded') === "true") {
      $( "#Country-Li-area" ).addClass("activeMenuState");
    }

});

```

```{r, echo = FALSE}
source('functions.R')
dict <- load_dict()
data <- load_data()
region_countries <- load_regions_countries()
```

```{r}
data <- data %>% filter(Region==params$region) %>% droplevels() %>% mutate(SI01 = as.character(SI01)) %>% arrange( SI01 )
```

```{r, echo = FALSE}
region_countries <- load_regions_countries()
n_unique_countries <- length( unique( data$SI01 ))
region_countries <- region_countries %>%
  filter(Region == params$region)
n_region_countries <- length( region_countries$Country)
```

`r str_to_title(as.english(n_unique_countries))` of `r n_region_countries` `r params$region` countries (`r round(100*( n_unique_countries / n_region_countries))`%) responded:  

`r pander( data$SI01 )`. 

```{r}
q5_start <- min(which(dict$`Question number` == "5"))
incomplete_surveys <- c()
for (i in 1:nrow(data)) {
  if (all(is.na(data[i, q5_start:nrow(dict)]))) {
    incomplete_surveys <- c(incomplete_surveys, i)
  }
}
incompletes <- FALSE
if( length( incomplete_surveys) > 0){
  incompletes <- TRUE
  excluded_countries <- paste( data$SI01[ incomplete_surveys ], "only provided initial demographic information; their responses are henceforth excluded.\n Non-responding countries are of concern in terms of arbovirus emergence and endemic transmission.")
} 
```

```{r eval=incompletes, results="asis"}
pander(excluded_countries)
```

```{r, out.width = '100%'}
load("../data/world_shp.rda")
library( leaflet )

# N.B. subsetting world_shp causes problems with certain versions of leaflet (?)
# leaving the following 2 lines for now in case they're useful later...
# rshape <- world_shp[ !is.na( world_shp@data$region ), ]
# rshape <- rshape[ rshape@data$region == params$region, ]

if( params$region != "WPRO" ){
  ll <- apply( coordinates(world_shp[ !is.na( world_shp@data$region ) & world_shp@data$region == params$region, ]), 2, mean )
} else{
  ll <- c( world_shp@data$LON[ which( world_shp@data$country == "Cambodia") ],
           world_shp@data$LAT[ which( world_shp@data$country == "Cambodia") ])
}
make_map(df = data %>% 
           dplyr::select(country = SI01) %>% 
           mutate( country = recode_factor(.x=country,
                                           "Bolivia (Plurinational State of)" = "Bolivia",
                                           "Saint Barthélemy" = "Saint Barthelemy",
                                           "United States of America" = "United States",
                                           "Venezuela (Bolivarian Republic of)" = "Venezuela") ) %>% 
           mutate(value = 'Participated'),
         pal = 'Set2', qualitative = TRUE, rev = FALSE, opacity = 0.95) %>%
  setView( lng = ll[1], lat = ll[2], zoom = case_when( params$region == "AMRO" ~ 2,
                                                       params$region == "EMRO" ~ 3,
                                                       params$region == "EURO" ~ 4,
                                                       params$region == "SEARO" ~ 3,
                                                       params$region == "WPRO" ~ 3) )
```
