---
title: "Regional laboratory diagnostic indicators"
---

```{r, include=FALSE, echo = FALSE}
# Basic knitr options
library(knitr)
opts_chunk$set(comment = NA, 
               echo = FALSE,
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE,
               fig.width = 9.64,
               fig.height = 5.9,
               fig.path = 'figures/')
ggplot2::theme_set(ggplot2::theme_bw())

# options(scipen = '999')
```

```{js}
element = document.getElementById('WHO_logo');
console.log(element)

$('#WHO_logo').click(function(e){
    console.log("Exists!")
});


window.onscroll = function() { scrollFunction() };

var navbar = document.getElementById("navbar");
var logoWhiteElement = document.getElementById("whiteLogoPosition")
var sticky = navbar.offsetTop;

function scrollFunction() {
  if (window.pageYOffset >= sticky) {
    navbar.classList.add("sticky");
    logoWhiteElement.classList.add("white_logo_appear");
  } else {
    navbar.classList.remove("sticky");
    logoWhiteElement.classList.remove("white_logo_appear");
  }
}

$(document).on('click', function (e){
    /* Global data  */
    var global_menu_opened = $('#global-navigation').hasClass('in');
    if(!$(e.target).closest('#global-navigation').length &&
        !$(e.target).is('#global-navigation') &&
        global_menu_opened === true){
            $('#global-navigation').collapse('toggle');
            $( "#Global-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#global-navigation').attr('aria-expanded') === "false") {
      $( "#Global-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#global-navigation').attr('aria-expanded') === "true") {
      $( "#Global-Li-area" ).addClass("activeMenuState");
    }

     /* Regional data  */
    var regional_menu_opened = $('#regional-navigation').hasClass('in');
    if(!$(e.target).closest('#regional-navigation').length &&
        !$(e.target).is('#regional-navigation') &&
        regional_menu_opened === true){
            $('#regional-navigation').collapse('toggle');
            $( "#Regional-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#regional-navigation').attr('aria-expanded') === "false") {
      $( "#Regional-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#regional-navigation').attr('aria-expanded') === "true") {
      $( "#Regional-Li-area" ).addClass("activeMenuState");
    }
     
     
     /* Country data  */
    var country_menu_opened = $('#country-navigation').hasClass('in');
    if(!$(e.target).closest('#country-navigation').length &&
        !$(e.target).is('#country-navigation') &&
        country_menu_opened === true){
            $('#country-navigation').collapse('toggle');
            $( "#Country-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#country-navigation').attr('aria-expanded') === "false") {
      $( "#Country-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#country-navigation').attr('aria-expanded') === "true") {
      $( "#Country-Li-area" ).addClass("activeMenuState");
    }


});

```

```{r, child="_sessioninfo.Rmd"}
```

```{r, echo = FALSE}
source('functions.R')
dict <- load_dict()
df <- load_data()
```

## Laboratory tests available 

#### Overall, what arboviral testing capacity(ies) is(are) available in your country? Please check all applicable boxes. (Question 17) 

```{r} 
# fig.height=8}

# relevant question: q17

responses <- get_responses("17")
qdf <- cbind( Region = df$Region, responses) %>% 
  pivot_longer(!Region, names_to="Testing", values_to="Response")
new_cols <- matrix( unlist( strsplit(qdf$Testing, "\\]\\[") ), ncol=2, byrow=T)
qdf <- qdf %>% 
  mutate(Arbovirus = new_cols[,1], Testing = new_cols[,2])
qdf$Response <- as.numeric( qdf$Response)
qdf <- qdf %>% 
  group_by(Region, Arbovirus, Testing) %>% 
  drop_na( Region ) %>% 
  summarize(Total = sum(Response, na.rm=T))
qdf$Arbovirus <- factor( qdf$Arbovirus )
qdf$Testing <- factor( qdf$Testing )

qdf %>% 
  pivot_wider(names_from=Testing, values_from=Total) %>% 
  regulartable %>% 
  merge_v(j = ~Region) %>% 
  valign(j = 1, valign = "top", part = "all") %>% 
  hline(i=5*(1:4)) %>% 
  colformat_num( na_str = "0" ) %>%
  fix_border_issues # %>%
  # autofit 

# ggplot(qdf, aes(x=Testing, y=Total, fill=Testing)) + 
#   geom_col() + 
#   facet_grid( Region ~ Arbovirus ) + 
#   theme(legend.position = "bottom",
#         legend.direction="horizontal",
#         axis.title.x=element_blank(),
#         axis.text.x=element_blank(),
#         axis.ticks.x=element_blank()) +
#   guides(fill = guide_legend(ncol = 2)) + 
#   scale_fill_manual(name = '',
#                     values = make_colors(length(unique(qdf$Testing))))

```
