---
title: "Regional surveillance capacity indicators"
---

```{r, include=FALSE, echo = FALSE}
# Basic knitr options
library(knitr)
opts_chunk$set(comment = NA, 
               echo = FALSE,
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE,
               fig.width = 9.64,
               fig.height = 5.9,
               fig.path = 'figures/')
ggplot2::theme_set(ggplot2::theme_bw())

# options(scipen = '999')
```

```{js}
element = document.getElementById('WHO_logo');
console.log(element)

$('#WHO_logo').click(function(e){
    console.log("Exists!")
});


window.onscroll = function() { scrollFunction() };

var navbar = document.getElementById("navbar");
var logoWhiteElement = document.getElementById("whiteLogoPosition")
var sticky = navbar.offsetTop;

function scrollFunction() {
  if (window.pageYOffset >= sticky) {
    navbar.classList.add("sticky");
    logoWhiteElement.classList.add("white_logo_appear");
  } else {
    navbar.classList.remove("sticky");
    logoWhiteElement.classList.remove("white_logo_appear");
  }
}

$(document).on('click', function (e){
    /* Global data  */
    var global_menu_opened = $('#global-navigation').hasClass('in');
    if(!$(e.target).closest('#global-navigation').length &&
        !$(e.target).is('#global-navigation') &&
        global_menu_opened === true){
            $('#global-navigation').collapse('toggle');
            $( "#Global-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#global-navigation').attr('aria-expanded') === "false") {
      $( "#Global-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#global-navigation').attr('aria-expanded') === "true") {
      $( "#Global-Li-area" ).addClass("activeMenuState");
    }

     /* Regional data  */
    var regional_menu_opened = $('#regional-navigation').hasClass('in');
    if(!$(e.target).closest('#regional-navigation').length &&
        !$(e.target).is('#regional-navigation') &&
        regional_menu_opened === true){
            $('#regional-navigation').collapse('toggle');
            $( "#Regional-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#regional-navigation').attr('aria-expanded') === "false") {
      $( "#Regional-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#regional-navigation').attr('aria-expanded') === "true") {
      $( "#Regional-Li-area" ).addClass("activeMenuState");
    }
     
     
     /* Country data  */
    var country_menu_opened = $('#country-navigation').hasClass('in');
    if(!$(e.target).closest('#country-navigation').length &&
        !$(e.target).is('#country-navigation') &&
        country_menu_opened === true){
            $('#country-navigation').collapse('toggle');
            $( "#Country-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#country-navigation').attr('aria-expanded') === "false") {
      $( "#Country-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#country-navigation').attr('aria-expanded') === "true") {
      $( "#Country-Li-area" ).addClass("activeMenuState");
    }


});

```


```{r, child="_sessioninfo.Rmd"}
```

```{r, echo = FALSE}
source('functions.R')
dict <- load_dict()
df <- load_data()
```

## Reportable arboviral diseases

#### Is reporting mandatory for any arboviral disease cases in your country? (Question 11) 

```{r}

# relevant question: q11

responses <- get_responses("11")
qdf <- data.frame(Region = df$Region, Response = responses) %>% 
  drop_na(Region) %>% 
  mutate( Response = factor( replace_na( as.character(Response), "Unanswered"))) %>%
  mutate( Response = fct_relevel(Response, "Yes", "No", "Unanswered")) %>% 
  group_by(Region, Response) %>%
  tally 
qdf %>% 
  pivot_wider(names_from=Response, values_from=n) %>%
  adorn_totals() %>%
  regulartable() %>%
  colformat_num( na_str = "0" ) %>%
  hline(i=4) # %>%
  # autofit 

# ggplot( qdf, 
#         aes( x = Response,
#              y = n,
#              fill = Response)) +
#   geom_col() +
#   facet_wrap( ~Region ) +
#   theme(legend.position = "bottom",
#         legend.direction="horizontal",
#         axis.title.x=element_blank(),
#         axis.text.x=element_blank(),
#         axis.ticks.x=element_blank()) +
#   guides(fill=guide_legend(ncol=3)) +
#   scale_fill_manual(name = '',
#                     values = make_colors(length(unique(qdf$Response)))) +
#   labs(title = "Mandatory reporting of cases", 
#        y = 'Responses')
  

```

#### For which of the following arboviral disease cases is reporting mandatory in your country? (Question 11b) 

```{r}

# relevant question: q11b

responses <- get_responses("11b")
qdf <- cbind(Region = df$Region, responses) %>% 
  pivot_longer(!Region, names_to="Arbovirus", values_to="Response") %>% 
  mutate( Response = factor( replace_na( as.character(Response), "Unanswered"))) %>%
  group_by(Region, Arbovirus, Response) %>% 
  tally
qdf$Response <- str_to_sentence(gsub("Mandatory reporting of ", "", qdf$Response))
qdf %>% 
  pivot_wider(names_from=Response, values_from=n) %>% 
  drop_na(Region) %>% 
  relocate("Confirmed cases only", .after="All suspect cases") %>%
  regulartable() %>% 
  merge_v(j = ~Region) %>% 
  valign(j = 1, valign = "top", part = "all") %>% 
  hline(i=6*(1:4)) %>% 
  colformat_num(na_str = "0") %>%
  fix_border_issues() %>%
  width( j=2, width=2 ) # %>%
  # autofit() 

# ggplot(qdf, aes(x=Response, y=n, fill=Response)) + 
#   geom_col() + 
#   facet_grid( Region ~ Arbovirus ) +
#   theme(legend.position = "bottom",
#         legend.direction="horizontal",
#         axis.title.x=element_blank(),
#         axis.text.x=element_blank(),
#         axis.ticks.x=element_blank()) +
#   guides(fill=guide_legend(ncol=4)) +
#   scale_fill_manual(name = '',
#                     values = make_colors(length(unique(qdf$Response)))) +
#   labs(title = "Regional reporting of cases", 
#        y = 'Responses')

```
