---
title: " "
---

```{r, include=FALSE, echo = FALSE}
# Basic knitr options
library(knitr)
opts_chunk$set(comment = NA, 
               echo = FALSE,
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE,
               fig.width = 9.64,
               fig.height = 5.9,
               fig.path = 'figures/')
ggplot2::theme_set(ggplot2::theme_bw())

# options(scipen = '999')
```

```{js}
element = document.getElementById('WHO_logo');
console.log(element)

$('#WHO_logo').click(function(e){
    console.log("Exists!")
});


window.onscroll = function() { scrollFunction() };

var navbar = document.getElementById("navbar");
var logoWhiteElement = document.getElementById("whiteLogoPosition")
var sticky = navbar.offsetTop;

function scrollFunction() {
  if (window.pageYOffset >= sticky) {
    navbar.classList.add("sticky");
    logoWhiteElement.classList.add("white_logo_appear");
  } else {
    navbar.classList.remove("sticky");
    logoWhiteElement.classList.remove("white_logo_appear");
  }
}

$(document).on('click', function (e){
    /* Global data  */
    var global_menu_opened = $('#global-navigation').hasClass('in');
    if(!$(e.target).closest('#global-navigation').length &&
        !$(e.target).is('#global-navigation') &&
        global_menu_opened === true){
            $('#global-navigation').collapse('toggle');
            $( "#Global-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#global-navigation').attr('aria-expanded') === "false") {
      $( "#Global-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#global-navigation').attr('aria-expanded') === "true") {
      $( "#Global-Li-area" ).addClass("activeMenuState");
    }

     /* Regional data  */
    var regional_menu_opened = $('#regional-navigation').hasClass('in');
    if(!$(e.target).closest('#regional-navigation').length &&
        !$(e.target).is('#regional-navigation') &&
        regional_menu_opened === true){
            $('#regional-navigation').collapse('toggle');
            $( "#Regional-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#regional-navigation').attr('aria-expanded') === "false") {
      $( "#Regional-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#regional-navigation').attr('aria-expanded') === "true") {
      $( "#Regional-Li-area" ).addClass("activeMenuState");
    }
     
     
     /* Country data  */
    var country_menu_opened = $('#country-navigation').hasClass('in');
    if(!$(e.target).closest('#country-navigation').length &&
        !$(e.target).is('#country-navigation') &&
        country_menu_opened === true){
            $('#country-navigation').collapse('toggle');
            $( "#Country-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#country-navigation').attr('aria-expanded') === "false") {
      $( "#Country-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#country-navigation').attr('aria-expanded') === "true") {
      $( "#Country-Li-area" ).addClass("activeMenuState");
    }


});

```

```{r, echo = FALSE}
source('functions.R')
dict <- load_dict()
data <- load_data()
```


```{r}
data <- data %>% filter(Region=='EMRO') %>% droplevels() %>% mutate(SI01 = as.character(SI01)) %>% arrange( SI01 )
```

<ul class="custom_tabbar">
<li class="custom_tabbar__list-active"><a href="EMRO_Q11.html">EMRO</a></li>
<li><a href="EURO_Q11.html">EURO</a></li>
<li><a href="SEARO_Q11.html">SEARO</a></li>
<li><a href="WPRO_Q11.html">WPRO</a></li>
</ul>

```{r}

caption <- "Reportable diseases by case classification status (ref Q11b, 11c)"
q11b <- get_responses("11b")
q11b <- cbind(Country = data$SI01, q11b) %>%
  select(-"Other ") %>% 
  pivot_longer(!Country, names_to = "Arbovirus", values_to = "Response")
q11b$Response <- str_to_sentence(gsub("Mandatory reporting of ", "", q11b$Response))
q11b <- q11b %>%
  mutate( Arbovirus = recode_factor(.x = Arbovirus,
                                    "Chikungunya" = "CHIKV",
                                    "Dengue" = "DENV",
                                    "Yellow fever" = "YFV",
                                    "Zika (congenital)" = "ZIKV (C)",
                                    "Zika (non-congenital)" = "ZIKV (NC)")) %>%
  mutate( Response = recode_factor( .x = Response,
                                    "All suspect cases" = "S",
                                    "Confirmed cases only" = "C",
                                    "Not reportable" = "N")) %>%
  pivot_wider(names_from = Arbovirus, values_from = Response) 

q11c <- get_responses("11c")
idx <- which( grepl("Arbovirus",colnames(q11c)))
arboviruses <- cbind( Country=data$SI01, q11c[,idx]) %>%
  pivot_longer(!Country) %>%
  select( Country, Arbovirus=value)
reporting <- cbind( Country=data$SI01, q11c[,-idx]) %>%
  pivot_longer(!Country) %>%
  select( Country, Reporting=value)
idx <- grep("suspect", str_to_lower(reporting$Reporting))
reporting$Reporting[idx] <- " (S)"
idx <- grep("confirm", str_to_lower(reporting$Reporting))
reporting$Reporting[idx] <- " (C)"
idx <- grep("not", str_to_lower(reporting$Reporting))
reporting$Reporting[idx] <- " (N)"
reporting$Reporting[ is.na( reporting$Reporting) ] <- ""
q11c <- cbind(arboviruses, Reporting = reporting$Reporting) %>%
  unite( "Other", Arbovirus:Reporting, sep = "")
idx <- which( q11c$Other == "NA" )
q11c <- q11c[-idx,]
q11c <- q11c %>% 
  group_by( Country ) %>% 
  summarize( Other = paste(Other, collapse=", "))

left_join( q11b, q11c) %>%
  regulartable() %>%
  merge_v(j = ~Country ) %>% 
  set_caption(caption) %>% autofit()

 


```
