
```{r}
amro <- params$region == "AMRO"
```

#### Countries with clinical guidelines for healthcare workers on diagnosis and clinical management of cases and severe cases of _Aedes_-borne arboviral diseases (ref Q21)

```{r eval = !amro}
responses <- get_responses("21")
responses <- cbind(Country=data$SI01, responses) 

available <- paste0( responses$Country[which(responses$Response == "Yes")], collapse = ", " )
no_answer <- paste0( responses$Country[which(is.na(responses$Response))], collapse = ", " )
no_guidelines <- paste0( responses$Country[which(responses$Response == "No")], collapse = ", " )

guidelines <- paste0( "The following countries indicated availability of clinical guidelines: ",
                      available,
                      ". \n",
                      no_answer,
                      " did not answer the question and ",
                      no_guidelines,
                      " indicated no guidelines.")

```

`r if(!amro){ guidelines }`

<br> 

#### Training for healthcare workers on clinical diagnosis and management of _Aedes_-borne arboviral diseases (ref Q24)

```{r eval = !amro}
responses <- get_responses("24")
colnames(responses) <- c("Response","Training")
cbind(Country=data$SI01, responses) %>%
  mutate( Response = recode_factor(.x = Response,
                                   "Yes, specific training is provided. If so, please specify:"="X",
                                   "No"=" ")) %>%
  filter(Response=="X") %>% 
  select(-Response) %>%
  replace_na( list(Training="Not specified")) %>%
  regulartable() %>% 
  theme_zebra(odd_header="#048ECA", odd_body = "#D6EAF8") %>% 
  color( color="#FFFFFF", part="header" ) %>% 
  valign( valign = "top", part="header" ) %>%
  padding( padding.top = 10, part="all") %>%
  padding( padding.bottom = 10, part="all") %>%
  autofit()
```

```{r eval = amro}
disclaimer <- "#### Questions 21 and 24 were not included in the dataset shared with AMRO for completion. Please see the Arbovirus Survey Overview for more information."
```

<br>

`r if(amro){ disclaimer }`
