---
title: " "
---

```{r, include=FALSE, echo = FALSE}
# Basic knitr options
library(knitr)
opts_chunk$set(comment = NA, 
               echo = FALSE,
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE,
               fig.width = 9.64,
               fig.height = 5.9,
               fig.path = 'figures/')
ggplot2::theme_set(ggplot2::theme_bw())

# options(scipen = '999')
```

```{js}
element = document.getElementById('WHO_logo');
console.log(element)

$('#WHO_logo').click(function(e){
    console.log("Exists!")
});


window.onscroll = function() { scrollFunction() };

var navbar = document.getElementById("navbar");
var logoWhiteElement = document.getElementById("whiteLogoPosition")
var sticky = navbar.offsetTop;

function scrollFunction() {
  if (window.pageYOffset >= sticky) {
    navbar.classList.add("sticky");
    logoWhiteElement.classList.add("white_logo_appear");
  } else {
    navbar.classList.remove("sticky");
    logoWhiteElement.classList.remove("white_logo_appear");
  }
}

$(document).on('click', function (e){
    /* Global data  */
    var global_menu_opened = $('#global-navigation').hasClass('in');
    if(!$(e.target).closest('#global-navigation').length &&
        !$(e.target).is('#global-navigation') &&
        global_menu_opened === true){
            $('#global-navigation').collapse('toggle');
            $( "#Global-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#global-navigation').attr('aria-expanded') === "false") {
      $( "#Global-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#global-navigation').attr('aria-expanded') === "true") {
      $( "#Global-Li-area" ).addClass("activeMenuState");
    }

     /* Regional data  */
    var regional_menu_opened = $('#regional-navigation').hasClass('in');
    if(!$(e.target).closest('#regional-navigation').length &&
        !$(e.target).is('#regional-navigation') &&
        regional_menu_opened === true){
            $('#regional-navigation').collapse('toggle');
            $( "#Regional-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#regional-navigation').attr('aria-expanded') === "false") {
      $( "#Regional-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#regional-navigation').attr('aria-expanded') === "true") {
      $( "#Regional-Li-area" ).addClass("activeMenuState");
    }
     
     
     /* Country data  */
    var country_menu_opened = $('#country-navigation').hasClass('in');
    if(!$(e.target).closest('#country-navigation').length &&
        !$(e.target).is('#country-navigation') &&
        country_menu_opened === true){
            $('#country-navigation').collapse('toggle');
            $( "#Country-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#country-navigation').attr('aria-expanded') === "false") {
      $( "#Country-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#country-navigation').attr('aria-expanded') === "true") {
      $( "#Country-Li-area" ).addClass("activeMenuState");
    }


});

```

```{r, echo = FALSE}
source('functions.R')
dict <- load_dict()
data <- load_data()
```


```{r}
data <- data %>% filter(Region=='EMRO') %>% droplevels() %>% mutate(SI01 = as.character(SI01)) %>% arrange( SI01 )
```

<ul class="custom_tabbar">
<li class="custom_tabbar__list-active"><a href="EMRO_Q29.html">EMRO</a></li>
<li><a href="EURO_Q29.html">EURO</a></li>
<li><a href="SEARO_Q29.html">SEARO</a></li>
<li><a href="WPRO_Q29.html">WPRO</a></li>
</ul>

```{r}

caption <- "Mosquito surveillance and identification (ref Q29, 30, 31)"
q29 <- get_responses("29")
q29 <- q29 %>% 
  mutate( Response = recode_factor(.x=Response,
                                   "Yes"="X",
                                   "No"=" ")) %>%
  rename("Adult surveillance"="Response") 
q30 <- get_responses("30")
q30 <- q30 %>% 
  mutate( Response = recode_factor(.x=Response,
                                   "Yes"="X",
                                   "No"=" ")) %>%
  rename("Larval/pupal surveillance"="Response")
q31 <- get_responses("31")
q31 <- q31 %>% 
  mutate( Response = recode_factor(.x=Response,
                                   "Yes"="X",
                                   "No"=" ")) %>%
  rename("Trapped mosquitoes identified to species"="Response")
cbind(Country=data$SI01, q29, q30, q31) %>%
  regulartable() %>%
  set_caption(caption) %>% autofit()

 

```
