
```{r}
amro <- params$region == "AMRO"
```

#### Arbovirus surveillance staff at the national level prior to COVID-19 outbreak (Q58)

```{r eval = !amro}
responses <- get_responses("58")
responses <- cbind(Country = data$SI01, responses) %>%
  pivot_longer(!Country)
new_cols <- matrix(unlist(strsplit(responses$name, "\\]\\[")), ncol = 2, byrow = T)
responses %>%
  mutate(Level = new_cols[, 1], Staff = new_cols[, 2]) %>%
  select(-name, -Level) %>% 
  pivot_wider( names_from = Staff, values_from = value) %>% 
  rename( "Support staff" = "Support staff (administration; logistics; other)") %>%
  regulartable() %>% 
  theme_zebra(odd_header="#048ECA", odd_body = "#D6EAF8") %>% 
  color( color="#FFFFFF", part="header" ) %>% 
  align( j=2:6, align="center", part="all" ) %>%
  valign( valign = "top", part="header" ) %>%
  padding( padding.top = 10, part="all") %>%
  padding( padding.bottom = 10, part="all") %>%
  autofit() 

```

<br>

#### Number of arbovirus surveillance staff needed to ensure adequate capacity (Q59)

```{r eval = !amro}
responses <- get_responses("59")
responses <- cbind(Country = data$SI01, responses) %>%
  pivot_longer(!Country)
new_cols <- matrix(unlist(strsplit(responses$name, "\\]\\[")), ncol = 2, byrow = T)
responses %>%
  mutate(Level = new_cols[, 1], Staff = new_cols[, 2]) %>%
  select(-name, -Level) %>% 
  pivot_wider( names_from = Staff, values_from = value) %>% 
  rename( "Support staff" = "Support staff (administration; logistics; other)") %>%
  regulartable() %>% 
  theme_zebra(odd_header="#048ECA", odd_body = "#D6EAF8") %>% 
  color( color="#FFFFFF", part="header" ) %>% 
  align( j=2:6, align="center", part="all" ) %>%
  valign( valign = "top", part="header" ) %>%
  padding( padding.top = 10, part="all") %>%
  padding( padding.bottom = 10, part="all") %>%
  autofit() 

```

<br>

#### Additional details regarding current and required staffing numbers (Q60)

```{r eval = !amro}
responses <- get_responses("60")
cbind(Country = data$SI01, responses) %>%
  regulartable() %>% 
  theme_zebra(odd_header="#048ECA", odd_body = "#D6EAF8") %>% 
  color( color="#FFFFFF", part="header" ) %>% 
  valign( valign = "top", part="header" ) %>%
  padding( padding.top = 10, part="all") %>%
  padding( padding.bottom = 10, part="all") %>%
  autofit() 
```

```{r eval = amro}
disclaimer <- "#### These questions were not included in the dataset shared with AMRO for completion. Please see the Arbovirus Survey Overview for more information."
```

<br>

`r if(amro){ disclaimer }`
