
```{r}
amro <- params$region == "AMRO"
```

#### Access to expertise in clinical management of arboviruses (Q61)

```{r eval = !amro}
responses <- get_responses("61")
other <- responses %>% select(Other)
responses <- responses %>% select(-Other)

responses <- responses %>%
  mutate_at( .vars=vars(colnames(responses)),
             .funs = forcats::fct_recode,
             "X" = "Yes",
             " " = "Not selected")

if( any(!is.na(other$Other))){
  responses <- cbind( responses, other)
}

cbind(Country=data$SI01, responses) %>%
  regulartable() %>% 
  theme_zebra(odd_header="#048ECA", odd_body = "#D6EAF8") %>% 
  color( color="#FFFFFF", part="header" ) %>% 
  valign( valign = "top", part="header" ) %>%
  align( align="center", part="all" ) %>%
  align( j=1, align="left", part="all") %>%
  padding( padding.top = 10, part="all") %>%
  padding( padding.bottom = 10, part="all") %>%
  autofit()

```

<br>

#### Access to expertise in arbovirus epidemiology (Q62) 

```{r eval = !amro}
responses <- get_responses("62")
other <- responses %>% select(Other)
responses <- responses %>% select(-Other)

responses <- responses %>%
  mutate_at( .vars=vars(colnames(responses)),
             .funs = forcats::fct_recode,
             "X" = "Yes",
             " " = "Not selected")

if( any(!is.na(other$Other))){
  responses <- cbind( responses, other)
}

cbind(Country=data$SI01, responses) %>%
  regulartable() %>% 
  theme_zebra(odd_header="#048ECA", odd_body = "#D6EAF8") %>% 
  color( color="#FFFFFF", part="header" ) %>% 
  valign( valign = "top", part="header" ) %>%
  align( align="center", part="all" ) %>%
  align( j=1, align="left", part="all") %>%
  padding( padding.top = 10, part="all") %>%
  padding( padding.bottom = 10, part="all") %>%
  autofit()

```

<br>

#### Access to expertise in arbovirus laboratory diagnosis (Q63)

```{r eval = !amro}
responses <- get_responses("63")
other <- responses %>% select(Other)
responses <- responses %>% select(-Other)

responses <- responses %>%
  mutate_at( .vars=vars(colnames(responses)),
             .funs = forcats::fct_recode,
             "X" = "Yes",
             " " = "Not selected")

if( any(!is.na(other$Other))){
  responses <- cbind( responses, other)
}

cbind(Country=data$SI01, responses) %>%
  regulartable() %>% 
  theme_zebra(odd_header="#048ECA", odd_body = "#D6EAF8") %>% 
  color( color="#FFFFFF", part="header" ) %>% 
  valign( valign = "top", part="header" ) %>%
  align( align="center", part="all" ) %>%
  align( j=1, align="left", part="all") %>%
  padding( padding.top = 10, part="all") %>%
  padding( padding.bottom = 10, part="all") %>%
  autofit()

```

<br>

#### Access to expertise in entomology (Q64)

```{r eval = !amro}
responses <- get_responses("64")
other <- responses %>% select(Other)
responses <- responses %>% select(-Other)

responses <- responses %>%
  mutate_at( .vars=vars(colnames(responses)),
             .funs = forcats::fct_recode,
             "X" = "Yes",
             " " = "Not selected")

if( any(!is.na(other$Other))){
  responses <- cbind( responses, other)
}

cbind(Country=data$SI01, responses) %>%
  regulartable() %>% 
  theme_zebra(odd_header="#048ECA", odd_body = "#D6EAF8") %>% 
  color( color="#FFFFFF", part="header" ) %>% 
  valign( valign = "top", part="header" ) %>%
  align( align="center", part="all" ) %>%
  align( j=1, align="left", part="all") %>%
  padding( padding.top = 10, part="all") %>%
  padding( padding.bottom = 10, part="all") %>%
  autofit()

```

```{r eval = amro}
disclaimer <- "#### These questions were not included in the dataset shared with AMRO for completion. Please see the Arbovirus Survey Overview for more information."
```

<br>

`r if(amro){ disclaimer }`

