---
title: ' '
pagetitle: 'ALL about'
output:
  html_document:
    includes:
      in_header: ALL_about_header.html
params:
  region: ALL
---

```{r, include=FALSE, echo = FALSE}
# Basic knitr options
library(knitr)
opts_chunk$set(comment = NA, 
               echo = FALSE,
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE,
               fig.width = 9.64,
               fig.height = 5.9,
               fig.path = 'figures/')
ggplot2::theme_set(ggplot2::theme_bw())

# options(scipen = '999')
```


```{js}
// Region dropdown
/* When the user clicks on the button,
toggle between hiding and showing the dropdown content */
function myFunction() {
  document.getElementById("myDropdown").classList.toggle("show");
}

// Close the dropdown menu if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {
    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
// end region dropdown

element = document.getElementById('WHO_logo');
console.log(element)

$('#WHO_logo').click(function(e){
    console.log("Exists!")
});


window.onscroll = function() { scrollFunction() };

var navbar = document.getElementById("navbar");
var logoWhiteElement = document.getElementById("whiteLogoPosition")
var sticky = navbar.offsetTop;

function scrollFunction() {
  if (window.pageYOffset >= sticky) {
    navbar.classList.add("sticky");
    logoWhiteElement.classList.add("white_logo_appear");
  } else {
    navbar.classList.remove("sticky");
    logoWhiteElement.classList.remove("white_logo_appear");
  }
}

$(document).on('click', function (e){
    /* Global data  */
    var global_menu_opened = $('#overview-navigation').hasClass('in');
    if(!$(e.target).closest('#overview-navigation').length &&
        !$(e.target).is('#overview-navigation') &&
        global_menu_opened === true){
            $('#overview-navigation').collapse('toggle');
            $( "#Overview-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#overview-navigation').attr('aria-expanded') === "false") {
      $( "#Overview-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#overview-navigation').attr('aria-expanded') === "true") {
      $( "#Overview-Li-area" ).addClass("activeMenuState");
    }

     /* Regional data  */
    var regional_menu_opened = $('#regional-navigation').hasClass('in');
    if(!$(e.target).closest('#regional-navigation').length &&
        !$(e.target).is('#regional-navigation') &&
        regional_menu_opened === true) {
            $('#regional-navigation').collapse('toggle');
            $( "#Regional-Li-area" ).removeClass("activeMenuState");
    }
    
    /* regional-navigation-arboviral-disease data  */
    var regional_menu_opened = $('#regional-navigation-arboviral-disease').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-arboviral-disease').length &&
        !$(e.target).is('#regional-navigation-arboviral-disease') &&
        regional_menu_opened === true) {
            $('#regional-navigation-arboviral-disease').collapse('toggle');
    }
    
    /* regional-navigation__arbrovirus_lab_capacity data  */
    var regional_menu_opened = $('#regional-navigation__arbrovirus_lab_capacity').hasClass('in');
    if(!$(e.target).closest('#regional-navigation__arbrovirus_lab_capacity').length &&
        !$(e.target).is('#regional-navigation__arbrovirus_lab_capacity') &&
        regional_menu_opened === true) {
            $('#regional-navigation__arbrovirus_lab_capacity').collapse('toggle');
    }
    
    /* regional-navigation__surveillance_staffing data  */
    var regional_menu_opened = $('#regional-navigation__surveillance_staffing').hasClass('in');
    if(!$(e.target).closest('#regional-navigation__surveillance_staffing').length &&
        !$(e.target).is('#regional-navigation__surveillance_staffing') &&
        regional_menu_opened === true) {
            $('#regional-navigation__surveillance_staffing').collapse('toggle');
    }
    
    /* regional-navigation__management_arboviral_disease_cases data  */
    var regional_menu_opened = $('#regional-navigation__management_arboviral_disease_cases').hasClass('in');
    if(!$(e.target).closest('#regional-navigation__management_arboviral_disease_cases').length &&
        !$(e.target).is('#regional-navigation__management_arboviral_disease_cases') &&
        regional_menu_opened === true) {
            $('#regional-navigation__management_arboviral_disease_cases').collapse('toggle');
    }
    
    /* regional-navigation__routine_vector_surveillance_and_control data  */
    var regional_menu_opened = $('#regional-navigation__routine_vector_surveillance_and_control').hasClass('in');
    if(!$(e.target).closest('#regional-navigation__routine_vector_surveillance_and_control').length &&
        !$(e.target).is('#regional-navigation__routine_vector_surveillance_and_control') &&
        regional_menu_opened === true) {
            $('#regional-navigation__routine_vector_surveillance_and_control').collapse('toggle');
    }
    
    /* regional-navigation__community_sensitization_and_participation data  */
    var regional_menu_opened = $('#regional-navigation__community_sensitization_and_participation').hasClass('in');
    if(!$(e.target).closest('#regional-navigation__community_sensitization_and_participation').length &&
        !$(e.target).is('#regional-navigation__community_sensitization_and_participation') &&
        regional_menu_opened === true) {
            $('#regional-navigation__community_sensitization_and_participation').collapse('toggle');
    }
    
    /* regional-navigation__preparedness_for_arboviral_outbreaks_epidemics data  */
    var regional_menu_opened = $('#regional-navigation__preparedness_for_arboviral_outbreaks_epidemics').hasClass('in');
    if(!$(e.target).closest('#regional-navigation__preparedness_for_arboviral_outbreaks_epidemics').length &&
        !$(e.target).is('#regional-navigation__preparedness_for_arboviral_outbreaks_epidemics') &&
        regional_menu_opened === true) {
            $('#regional-navigation__preparedness_for_arboviral_outbreaks_epidemics').collapse('toggle');
    }
    
    
    
    if ($('#regional-navigation').attr('aria-expanded') === "false") {
      $( "#Regional-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#regional-navigation').attr('aria-expanded') === "true") {
      $( "#Regional-Li-area" ).addClass("activeMenuState");
    }
     
     
     /* Country data  */
    var country_menu_opened = $('#country-navigation').hasClass('in');
    if(!$(e.target).closest('#country-navigation').length &&
        !$(e.target).is('#country-navigation') &&
        country_menu_opened === true){
            $('#country-navigation').collapse('toggle');
            $( "#Country-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#country-navigation').attr('aria-expanded') === "false") {
      $( "#Country-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#country-navigation').attr('aria-expanded') === "true") {
      $( "#Country-Li-area" ).addClass("activeMenuState");
    }


});

```


```{css, echo=FALSE}
h4 {
  text-align: center;
}
```


```{r, echo = FALSE}
source('functions.R')
dict <- load_dict()
data <- load_data()
```


```{r}
data <- data %>% mutate(SI01 = as.character(SI01)) %>% arrange( SI01 )
```
