---
title: ' '
pagetitle: 'EURO Q47'
output:
  html_document:
    includes:
      in_header: EURO_Q47_header.html
params:
  region: EURO
---

```{r, include=FALSE, echo = FALSE}
# Basic knitr options
library(knitr)
opts_chunk$set(comment = NA, 
               echo = FALSE,
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE)
# ggplot2::theme_set(ggplot2::theme_bw())
```

```{js}
// Region dropdown
/* When the user clicks on the button,
toggle between hiding and showing the dropdown content */
function myFunction() {
  document.getElementById("myDropdown").classList.toggle("show");
}

// Close the dropdown menu if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {
    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
// end region dropdown

element = document.getElementById('WHO_logo');
console.log(element)

$('#WHO_logo').click(function(e){
    console.log("Exists!")
});


window.onscroll = function() { scrollFunction() };

var navbar = document.getElementById("navbar");
var logoWhiteElement = document.getElementById("whiteLogoPosition")
var sticky = navbar.offsetTop;

function scrollFunction() {
  if (window.pageYOffset >= sticky) {
    navbar.classList.add("sticky");
    logoWhiteElement.classList.add("white_logo_appear");
  } else {
    navbar.classList.remove("sticky");
    logoWhiteElement.classList.remove("white_logo_appear");
  }
}

$(document).on('click', function (e){
    /* Global data  */
    var global_menu_opened = $('#overview-navigation').hasClass('in');
    if(!$(e.target).closest('#overview-navigation').length &&
        !$(e.target).is('#overview-navigation') &&
        global_menu_opened === true){
            $('#overview-navigation').collapse('toggle');
            $( "#Overview-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#overview-navigation').attr('aria-expanded') === "false") {
      $( "#Overview-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#overview-navigation').attr('aria-expanded') === "true") {
      $( "#Overview-Li-area" ).addClass("activeMenuState");
    }

     /* Regional data  */
    var regional_menu_opened = $('#regional-navigation').hasClass('in');
    if(!$(e.target).closest('#regional-navigation').length &&
        !$(e.target).is('#regional-navigation') &&
        regional_menu_opened === true) {
            $('#regional-navigation').collapse('toggle');
            $( "#Regional-Li-area" ).removeClass("activeMenuState");
    }
    
    /* #regional-navigation-disease-surveillance  */
    var regional_menu_opened = $('#regional-navigation-disease-surveillance').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-disease-surveillance').length &&
        !$(e.target).is('#regional-navigation-disease-surveillance') &&
        regional_menu_opened === true) {
            $('#regional-navigation-disease-surveillance').collapse('toggle');
    }
    
    /* #regional-navigation-lab-capacity  */
    var regional_menu_opened = $('#regional-navigation-lab-capacity').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-lab-capacity').length &&
        !$(e.target).is('#regional-navigation-lab-capacity') &&
        regional_menu_opened === true) {
            $('#regional-navigation-lab-capacity').collapse('toggle');
    }
    
    /* #regional-navigation-management  */
    var regional_menu_opened = $('#regional-navigation-management').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-management').length &&
        !$(e.target).is('#regional-navigation-management') &&
        regional_menu_opened === true) {
            $('#regional-navigation-management').collapse('toggle');
    }
    
    /* #regional-navigation-vector-surveillance  */
    var regional_menu_opened = $('#regional-navigation-vector-surveillance').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-vector-surveillance').length &&
        !$(e.target).is('#regional-navigation-vector-surveillance') &&
        regional_menu_opened === true) {
            $('#regional-navigation-vector-surveillance').collapse('toggle');
    }
    
    /* #regional-navigation-community  */
    var regional_menu_opened = $('#regional-navigation-community').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-community').length &&
        !$(e.target).is('#regional-navigation-community') &&
        regional_menu_opened === true) {
            $('#regional-navigation-community').collapse('toggle');
    }
    
    /* #regional-navigation-preparedness  */
    var regional_menu_opened = $('#regional-navigation-preparedness').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-preparedness').length &&
        !$(e.target).is('#regional-navigation-preparedness') &&
        regional_menu_opened === true) {
            $('#regional-navigation-preparedness').collapse('toggle');
    }
    
    /* #regional-navigation-surveillance-staffing  */
    var regional_menu_opened = $('#regional-navigation-surveillance-staffing').hasClass('in');
    if(!$(e.target).closest('#regional-navigation-surveillance-staffing').length &&
        !$(e.target).is('#regional-navigation-surveillance-staffing') &&
        regional_menu_opened === true) {
            $('#regional-navigation-surveillance-staffing').collapse('toggle');
    }
    
    if ($('#regional-navigation').attr('aria-expanded') === "false") {
      $( "#Regional-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#regional-navigation').attr('aria-expanded') === "true") {
      $( "#Regional-Li-area" ).addClass("activeMenuState");
    }
     
     /* Country data  */
    var country_menu_opened = $('#country-navigation').hasClass('in');
    if(!$(e.target).closest('#country-navigation').length &&
        !$(e.target).is('#country-navigation') &&
        country_menu_opened === true){
            $('#country-navigation').collapse('toggle');
            $( "#Country-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#country-navigation').attr('aria-expanded') === "false") {
      $( "#Country-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#country-navigation').attr('aria-expanded') === "true") {
      $( "#Country-Li-area" ).addClass("activeMenuState");
    }

});

```

```{css, echo=FALSE}
h4 {
  text-align: center;
}
```

```{r, echo = FALSE}
source('functions.R')
dict <- load_dict()
data <- load_data()
```

```{r}
data <- data %>% filter(Region==params$region) %>% droplevels() %>% mutate(SI01 = as.character(SI01)) %>% arrange( SI01 )
```

#### Outbreak committee presence, staff training, contingency plan and emergency funding (ref Q47, 48, 52, 53)

```{r}
q47 <- get_responses("47") %>%
  rename( "Outbreak committee in place" = Response)
q48 <- get_responses("48") %>%
  rename( "Staff/committee training for outbreaks" = Response)

q52 <- get_responses("52")

emergency_fund <- c()
for(i in 1:nrow(q52)){
  col = which( q52[i,] == "Yes")
  if( length(col) > 0 ){
    emergency_fund <- c( emergency_fund, paste0(names(q52)[col], collapse="\n"))
  } else{
    emergency_fund <- c(emergency_fund, NA)
  }
}

q53 <- get_responses("53") %>%
  rename( "Contingency plan for healthcare services in emergencies" = Response)

cbind(Country=data$SI01, q47, q48, q53, "Emergency fund" = emergency_fund) %>%
  regulartable() %>% 
  theme_zebra(odd_header="#048ECA", odd_body = "#D6EAF8") %>% 
  color( color="#FFFFFF", part="header" ) %>% 
  autofit()
```

<br>

#### Established collaborations with institutions or agencies for arboviral outbreaks (ref Q50)

```{r}
responses <- get_responses("50")
colnames( responses ) <- c("Response", "Institutions")
cbind(Country=data$SI01, responses) %>%
  mutate( Response = recode_factor(.x = Response,
                                   "Yes. If so, please specify institutions/agencies in the comments field:"="X",
                                   "No"=" ")) %>%
  filter( Response == "X" ) %>%
  select(-Response) %>% 
  regulartable() %>% 
  theme_zebra(odd_header="#048ECA", odd_body = "#D6EAF8") %>% 
  color( color="#FFFFFF", part="header" ) %>% 
  autofit()
```
