---
title: ' '
pagetitle: 'WPRO Q5'
output:
  html_document:
    includes:
      in_header: WPRO_Q5_header.html
params:
  region: WPRO
---

```{r, include=FALSE, echo = FALSE}
# Basic knitr options
library(knitr)
opts_chunk$set(comment = NA, 
               echo = FALSE,
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE,
               fig.width = 9.64,
               fig.height = 5.9,
               fig.path = 'figures/')
ggplot2::theme_set(ggplot2::theme_bw())

# options(scipen = '999')
```


```{js}
element = document.getElementById('WHO_logo');
console.log(element)

$('#WHO_logo').click(function(e){
    console.log("Exists!")
});


window.onscroll = function() { scrollFunction() };

var navbar = document.getElementById("navbar");
var logoWhiteElement = document.getElementById("whiteLogoPosition")
var sticky = navbar.offsetTop;

function scrollFunction() {
  if (window.pageYOffset >= sticky) {
    navbar.classList.add("sticky");
    logoWhiteElement.classList.add("white_logo_appear");
  } else {
    navbar.classList.remove("sticky");
    logoWhiteElement.classList.remove("white_logo_appear");
  }
}

$(document).on('click', function (e){
    /* Global data  */
    var global_menu_opened = $('#overview-navigation').hasClass('in');
    if(!$(e.target).closest('#overview-navigation').length &&
        !$(e.target).is('#overview-navigation') &&
        global_menu_opened === true){
            $('#overview-navigation').collapse('toggle');
            $( "#Overview-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#overview-navigation').attr('aria-expanded') === "false") {
      $( "#Overview-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#overview-navigation').attr('aria-expanded') === "true") {
      $( "#Overview-Li-area" ).addClass("activeMenuState");
    }

     /* Regional data  */
    var regional_menu_opened = $('#regional-navigation').hasClass('in');
    if(!$(e.target).closest('#regional-navigation').length &&
        !$(e.target).is('#regional-navigation') &&
        regional_menu_opened === true){
            $('#regional-navigation').collapse('toggle');
            $( "#Regional-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#regional-navigation').attr('aria-expanded') === "false") {
      $( "#Regional-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#regional-navigation').attr('aria-expanded') === "true") {
      $( "#Regional-Li-area" ).addClass("activeMenuState");
    }
     
     
     /* Country data  */
    var country_menu_opened = $('#country-navigation').hasClass('in');
    if(!$(e.target).closest('#country-navigation').length &&
        !$(e.target).is('#country-navigation') &&
        country_menu_opened === true){
            $('#country-navigation').collapse('toggle');
            $( "#Country-Li-area" ).removeClass("activeMenuState");
    }
    
    if ($('#country-navigation').attr('aria-expanded') === "false") {
      $( "#Country-Li-area" ).removeClass("activeMenuState");
    }
    if ($('#country-navigation').attr('aria-expanded') === "true") {
      $( "#Country-Li-area" ).addClass("activeMenuState");
    }


});

```


```{css, echo=FALSE}
h4 {
  text-align: center;
}
```


```{r, echo = FALSE}
source('functions.R')
dict <- load_dict()
data <- load_data()
```


```{r}
data <- data %>% filter(Region==params$region) %>% droplevels() %>% mutate(SI01 = as.character(SI01)) %>% arrange( SI01 )
```

### Documented arbovirus circulation

All responding countries reported transmission of at least one of chikungunya (CHIKV), dengue (DENV), and Zika (ZIKV) viruses. 
No countries reported autochthonous yellow fever virus transmission.

<br>

#### Arboviruses that have circulated autochthonously in the country at any time since 2000 (ref Q5)

```{r}
responses <- get_responses("5") 
other <- responses %>% select(Other)
responses <- responses %>% select(-Other)

responses <- cbind(Country = data$SI01, responses) %>% 
  pivot_longer(!Country, names_to="Arbovirus", values_to="Response") %>% 
  mutate( Arbovirus = recode_factor(.x = Arbovirus,
                                    "Chikungunya"="CHIKV",
                                    "Dengue"="DENV",
                                    "Yellow fever"="YFV",
                                    "Zika"="ZIKV")) %>% 
  mutate( Response = na_if(Response, "Not selected")) %>%
  mutate( Response = recode_factor(.x = Response, 
                                   "Yes"="X")) %>%
  pivot_wider( names_from=Arbovirus, values_from=Response) %>%
  mutate( Other = other$Other ) %>%
  filter( if_any(CHIKV:Other, ~ !is.na(.x)))

responses %>%
  regulartable() %>% 
  align( j = 2:5, align="center") %>% autofit() 
```
